"""Password Reset intent handler.

Graph API: POST /users/{id}/authentication/methods/{id}/resetPassword
Permission: UserAuthenticationMethod.ReadWrite.All

If no temporary password is provided, one is auto-generated by Graph.
"""

import logging
import secrets
import string
from typing import Any

from intents.base import BaseIntentHandler
from models.errors import GraphApiError

logger = logging.getLogger(__name__)


class PasswordResetHandler(BaseIntentHandler):

    def validate(self) -> None:
        self.require_field("User Email")

    def execute(self) -> dict[str, Any]:
        user_id, upn = self.resolve_user("User Email")

        temp_password = self.optional_field("Temporary Password")
        force_change = self.bool_field("Force Change on Login", default=True)

        # If no temp password provided, generate a strong random one
        if not temp_password:
            temp_password = self._generate_temp_password()

        # Reset password via Graph API
        # Using the PATCH /users/{id} approach (simpler, works with app permissions)
        body = {
            "passwordProfile": {
                "password": temp_password,
                "forceChangePasswordNextSignIn": force_change,
            }
        }

        resp = self.graph.patch(f"/users/{user_id}", body=body)

        if resp.status_code == 204:
            logger.info("Password reset successful for %s", upn)
            return {
                "status": "success",
                "user": upn,
                "force_change_on_login": force_change,
                "temp_password_provided": bool(self.optional_field("Temporary Password")),
            }

        self.raise_graph_error(resp, "Password Reset")

    @staticmethod
    def _generate_temp_password(length: int = 16) -> str:
        """Generate a strong temporary password meeting M365 complexity requirements."""
        # Ensure at least one of each required character type
        password = [
            secrets.choice(string.ascii_uppercase),
            secrets.choice(string.ascii_lowercase),
            secrets.choice(string.digits),
            secrets.choice("!@#$%^&*"),
        ]
        # Fill remaining length with mixed characters
        all_chars = string.ascii_letters + string.digits + "!@#$%^&*"
        password.extend(secrets.choice(all_chars) for _ in range(length - 4))

        # Shuffle to avoid predictable positions
        result = list(password)
        secrets.SystemRandom().shuffle(result)
        return "".join(result)
